# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='components',
            field=models.ManyToManyField(to='classes.Component'),
        ),
    ]
