# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20170318_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='superclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SuperClass'),
        ),
    ]
