# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='for_word',
            new_name='word',
        ),
    ]
