# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_word_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pref',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prefs.Pref'),
        ),
    ]
