# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20170318_1529'),
        ('words', '0006_word_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='class_name',
        ),
        migrations.AddField(
            model_name='word',
            name='class_name',
            field=models.ManyToManyField(to='classes.Class'),
        ),
    ]
